// [ START declaration ]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.2
// source: DTUservice.proto

package _

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SayHello_SexType int32

const (
	SayHello_Girl  SayHello_SexType = 0
	SayHello_man   SayHello_SexType = 1
	SayHello_woman SayHello_SexType = 2
	SayHello_body  SayHello_SexType = 4
)

// Enum value maps for SayHello_SexType.
var (
	SayHello_SexType_name = map[int32]string{
		0: "Girl",
		1: "man",
		2: "woman",
		4: "body",
	}
	SayHello_SexType_value = map[string]int32{
		"Girl":  0,
		"man":   1,
		"woman": 2,
		"body":  4,
	}
)

func (x SayHello_SexType) Enum() *SayHello_SexType {
	p := new(SayHello_SexType)
	*p = x
	return p
}

func (x SayHello_SexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SayHello_SexType) Descriptor() protoreflect.EnumDescriptor {
	return file_DTUservice_proto_enumTypes[0].Descriptor()
}

func (SayHello_SexType) Type() protoreflect.EnumType {
	return &file_DTUservice_proto_enumTypes[0]
}

func (x SayHello_SexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SayHello_SexType.Descriptor instead.
func (SayHello_SexType) EnumDescriptor() ([]byte, []int) {
	return file_DTUservice_proto_rawDescGZIP(), []int{0, 0}
}

type SayHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Int   int32  `protobuf:"varint,2,opt,name=int,proto3" json:"int,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SayHello) Reset() {
	*x = SayHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DTUservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHello) ProtoMessage() {}

func (x *SayHello) ProtoReflect() protoreflect.Message {
	mi := &file_DTUservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHello.ProtoReflect.Descriptor instead.
func (*SayHello) Descriptor() ([]byte, []int) {
	return file_DTUservice_proto_rawDescGZIP(), []int{0}
}

func (x *SayHello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SayHello) GetInt() int32 {
	if x != nil {
		return x.Int
	}
	return 0
}

func (x *SayHello) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SayHello_HeroInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age    int32            `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Gender SayHello_SexType `protobuf:"varint,2,opt,name=gender,proto3,enum=DTUApi.SayHello_SexType" json:"gender,omitempty"`
}

func (x *SayHello_HeroInfo) Reset() {
	*x = SayHello_HeroInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DTUservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHello_HeroInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHello_HeroInfo) ProtoMessage() {}

func (x *SayHello_HeroInfo) ProtoReflect() protoreflect.Message {
	mi := &file_DTUservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHello_HeroInfo.ProtoReflect.Descriptor instead.
func (*SayHello_HeroInfo) Descriptor() ([]byte, []int) {
	return file_DTUservice_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SayHello_HeroInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *SayHello_HeroInfo) GetGender() SayHello_SexType {
	if x != nil {
		return x.Gender
	}
	return SayHello_Girl
}

var File_DTUservice_proto protoreflect.FileDescriptor

var file_DTUservice_proto_rawDesc = []byte{
	0x0a, 0x10, 0x44, 0x54, 0x55, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x44, 0x54, 0x55, 0x41, 0x70, 0x69, 0x22, 0xc9, 0x01, 0x0a, 0x08, 0x53,
	0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x1a, 0x4e, 0x0a, 0x08, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67,
	0x65, 0x12, 0x30, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x44, 0x54, 0x55, 0x41, 0x70, 0x69, 0x2e, 0x53, 0x61, 0x79, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x2e, 0x53, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x67, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x22, 0x31, 0x0a, 0x07, 0x53, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x47, 0x69, 0x72, 0x6c, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x6d, 0x61, 0x6e, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x77, 0x6f, 0x6d, 0x61, 0x6e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x10, 0x04, 0x42, 0x06, 0x5a, 0x04, 0x44, 0x54, 0x55, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_DTUservice_proto_rawDescOnce sync.Once
	file_DTUservice_proto_rawDescData = file_DTUservice_proto_rawDesc
)

func file_DTUservice_proto_rawDescGZIP() []byte {
	file_DTUservice_proto_rawDescOnce.Do(func() {
		file_DTUservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_DTUservice_proto_rawDescData)
	})
	return file_DTUservice_proto_rawDescData
}

var file_DTUservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_DTUservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_DTUservice_proto_goTypes = []interface{}{
	(SayHello_SexType)(0),     // 0: DTUApi.SayHello.SexType
	(*SayHello)(nil),          // 1: DTUApi.SayHello
	(*SayHello_HeroInfo)(nil), // 2: DTUApi.SayHello.HeroInfo
}
var file_DTUservice_proto_depIdxs = []int32{
	0, // 0: DTUApi.SayHello.HeroInfo.gender:type_name -> DTUApi.SayHello.SexType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_DTUservice_proto_init() }
func file_DTUservice_proto_init() {
	if File_DTUservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_DTUservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DTUservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHello_HeroInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DTUservice_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DTUservice_proto_goTypes,
		DependencyIndexes: file_DTUservice_proto_depIdxs,
		EnumInfos:         file_DTUservice_proto_enumTypes,
		MessageInfos:      file_DTUservice_proto_msgTypes,
	}.Build()
	File_DTUservice_proto = out.File
	file_DTUservice_proto_rawDesc = nil
	file_DTUservice_proto_goTypes = nil
	file_DTUservice_proto_depIdxs = nil
}
