// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package service

import (
	"DTU/jobs/pulsar_tuya/biz"
	"DTU/jobs/pulsar_tuya/data"
)

// Injectors from wire.go:

func initializeNewGreeterService() *GreeterService {
	respEc := data.NewRespEc()
	greeterRepo := biz.NewGreeterRepo(respEc)
	tuyaRecv := data.NewTuyaRecv()
	tuyaPulsarData := biz.NewTuyaPulsarData(tuyaRecv)
	greeterService := NewGreeterService(greeterRepo, tuyaPulsarData)
	return greeterService
}
