// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package service

import (
	"DTU/jobs/http_alleyes/biz"
	"DTU/jobs/http_alleyes/data"
)

// Injectors from wire.go:

func initNewalleyesEventRecvData() *AlleyesEventRecvData {
	alleyesViolations := data.NewAlleyesViolations()
	alleyesRecv := biz.NewAlleyesRecv(alleyesViolations)
	alleyesEventRecvData := NewalleyesEventRecvData(alleyesRecv)
	return alleyesEventRecvData
}

// wire.go:

type AlleyesEventRecvData struct {
	BzData *biz.AlleyesRecv
}

func NewalleyesEventRecvData(recv *biz.AlleyesRecv) *AlleyesEventRecvData {
	return &AlleyesEventRecvData{recv}
}
